### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by sureshn04**
### **Done**

- 2FA auth using node js _(only for single user)_. 

### **Todo** 

- Update UI .

- Creating unique secrete key and store it in database for every single member.

- Login auth for osl members .

### packages used

1. Express js

2. Mongoose

3. Speakeasy

4. hbs

5. body-parser

6. qrcode

### CODE REVIEW

**Comment by shreevari** [comment]
Very well documented PR, if you could add the same informantion to the README, that'd be great.

**Comment by suresh-44** [comment]
OK , for the next pull request i will update in README

**Comment by sureshn04** [comment]
Thanks , for the next pull request i will update in README

**Comment by shreevari** [comment]
This has been open for too long now. I'm merging it.

**Pull request merged**
